// SPDX-License-Identifier: Apache-2.0.
// Copyright (C) 2026-present ahrs-debug-rig project and contributors.

//! IMU handler firmware entry point.

#![no_std]
#![no_main]
#![warn(clippy::all, clippy::pedantic, clippy::nursery)]
#![deny(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::todo,
    clippy::unreachable,
    missing_docs
)]
#![allow(clippy::future_not_send)]

mod drivers;
mod hal;
mod tasks;
mod types;

use crate::{
    hal::peripherals::SystemPeripherals,
    tasks::{
        status::{system_status_task},
        imu::imu_acquisition_task,
        transfer::transfer_data_task,
    },
};
use defmt_rtt as _;
use embassy_executor::Spawner;
use embassy_stm32::{Config, Peripherals};
use embassy_time::{Duration, Ticker, Timer};
use panic_probe as _;

// Including firmware config generated by AHRS Monitor.
include!(concat!(env!("OUT_DIR"), "/stm32_config.rs"));

/// IMU handler firmware entry point.
///
/// # Parameters
/// - `spawner` - given tasks spawner to handle.
#[embassy_executor::main]
async fn main(spawner: Spawner) -> ! {
    // Initializing system peripherals.
    let p: Peripherals = embassy_stm32::init(Config::default());
    let mut sp = SystemPeripherals::new(p).await;

    // Spawning task for handling system status update.
    let ticker = Ticker::every(Duration::from_millis(10));
    let _ = spawner.spawn(system_status_task(sp.status_led, ticker));

    // Spawning task for handling IMU data acquisition.
    let _ = spawner.spawn(imu_acquisition_task(sp.imu));

    // Spawning task for transferring IMU data.
    let _ = spawner.spawn(transfer_data_task(sp.spi, sp.spi_ss, sp.esp_ready));

    loop {
        sp.builtin_led.toggle();
        Timer::after_millis(1000).await;
    }
}
