// SPDX-License-Identifier: Apache-2.0.
// Copyright (C) 2026-present ahrs-debug-rig project and contributors.

//! AHRS gateway entry point.

#![no_std]
#![no_main]
#![deny(clippy::mem_forget)]
#![warn(clippy::all, clippy::correctness, clippy::suspicious)]
#![deny(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::todo,
    clippy::unreachable,
    missing_docs
)]

extern crate alloc;

pub mod hal;
mod tasks;
pub mod types;

use crate::{
    hal::SystemPeripherals,
    tasks::{
        recv::frame_acquisition_task,
        status::{set_system_status, system_status_task},
        transfer::transfer_data_task,
    },
    types::SystemStatus,
};
use alloc::string::ToString;
use embassy_executor::Spawner;
use embassy_time::{Duration, Ticker, Timer};
use esp_hal::clock::CpuClock;
use esp_println::println;

// This creates a default app-descriptor required by the esp-idf bootloader.
esp_bootloader_esp_idf::esp_app_desc!();

// Including firmware config generated by AHRS Monitor.
include!(concat!(env!("OUT_DIR"), "/esp32_config.rs"));

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());

    match SystemPeripherals::new(esp_hal::init(config), &spawner).await {
        Ok(sp) => {
            let ticker = Ticker::every(Duration::from_millis(10));

            let _ =
                spawner.spawn(system_status_task(sp.host.status_led, ticker));
            let _ = spawner.spawn(frame_acquisition_task(
                sp.host.spi,
                sp.host.dma_rx_buf,
                sp.host.esp_ready,
            ));
            let _ = spawner.spawn(transfer_data_task(sp.net_stack));
        }
        Err(e) => error("Error to initialize system peripherals", e).await,
    }

    loop {
        set_system_status(SystemStatus::Idle).await;
        Timer::after(Duration::from_millis(1000)).await;

        set_system_status(SystemStatus::Error).await;
        Timer::after(Duration::from_millis(500)).await;
    }
}

/// System panic handler.
///
/// # Parameters
/// - `info` - given information about a panic to handle.
#[panic_handler]
fn panic(info: &core::panic::PanicInfo) -> ! {
    println!("[PANIC] {}", info.to_string());
    loop {}
}

/// Handle fatal error.
///
/// # Parameters
/// - `msg` - given error message to print.
/// - `err` - given error to print.
pub async fn error(msg: &str, err: types::Error) {
    println!("[ERROR] {msg} {err}");

    loop {
        set_system_status(SystemStatus::Idle).await;
        Timer::after(Duration::from_millis(1000)).await;
        set_system_status(SystemStatus::Error).await;
    }
}
